---
title: "My Favourite Quotes"
output: html_document
---

<details>
<summary>**Adventure and Exploration**</summary>
- The interesting thing about being alive is that you're all in; no matter what you do, you're all in. This is going to kill you. So I think you might as well play the most magnificent game you can, while you're waiting because, do you have anything better to do?
- There is no better life purpose than to perish in attempting the great and impossible. 
- The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane. 
- It is one thing to study war and another to live the warrior's life. 
- Some stop because it’s hard. Some start because it’s hard. 
- Be willing to take calculated risk. 
- What if it can turn out better than you can imagine? 
</details>

<details>
<summary>**Solitude**</summary>
- How good might the best possible future be if the most effective sacrifice could be made? 
- What would happen if you spent one year giving it your all, doing exactly what you knew you needed to do? 
- A bad obsession is an act of consumption. A good obsession is an act of creation. 
- The two most powerful warriors are patience and time. 
- A calm mind creates art violently
- Not to feel exasperated, or defeated, or despondent because your days aren’t packed with wise and moral actions. But to get back up when you fail, to celebrate behaving like a human—however imperfectly—and fully embrace the pursuit that you’ve embarked on.
- The will to win is not nearly as important as the will to prepare to win. Everyone wants to win but not everyone wants to prepare to win. Preparing to win is where the determination that you will win is made. Once the game or test or project is underway, it is too late to prepare to win. The actual game, test or project is just the end of a long process of getting ready, in which the outcome was really determined. So if you want to win, you must prepare to win. Once you prepare to win, winning is almost anti-climatic.
</details>

<details>
<summary>**Urgency**</summary>
- Do it now. Do it now. Do it now.
- No one is going to come save you because you are perfectly capable of saving yourself.
- Indefatigable. Patient with outcomes and relentless with iteration. 
- Have a maniacal sense of urgency. 
- Now is the time to get serious about living your ideals. How long can you afford to put off who you really want to be? Your nobler self cannot wait any longer. Put your principles into practice - now. Stop the excuses and the procrastination.This is your life! You aren't a child anymore. The sooner you set yourself to your spiritual program, the happier you will be.The longer you wait, the more you'll be vulnerable to mediocrity and feel filled with shame and regret, because you know you are capable of better. From this instant on, vow to stop disappointing yourself. Separate yourself from the mob. Decide to be extraordinary and do what you need to do - now.
- Concentrate every minute like a Roman—like a man—On doing what’s in front of you with precise and genuine seriousness, tenderly, willingly, with justice. And on freeing yourself from all other distractions. Yes, you can—if you do everything as if it were the last thing you were doing in your life, And stop being aimless, stop letting your emotions override what your mind tells you, Stop being hypocritical, self-centered, irritable. You see how few things you have to do to live a satisfying and reverent life? If you can manage this, that’s all even the gods can ask of you.
</details>
